#org: 0rest5abara
app: todo-list
service: aws-sls-sep-22
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
#  region: us-east-1
#  versionFunctions: true

functions:
  getTodos:
    handler: src/handlers/get-todos.handler
    events:
      - httpApi:
          path: /todos
          method: get
  createTodo:
    handler: src/handlers/create-todo.handler
    events:
      - httpApi:
          path: /todos
          method: post

  getTodo:
    handler: src/handlers/get-todo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: get
  updateTodo:
    handler: src/handlers/update-todo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: patch
  deleteTodo:
    handler: src/handlers/delete-todo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: delete