service: aws-sls-sep-22
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: true

functions:
  getTodos:
    handler: src/handlers/get-todos.handler
    events:
      - httpApi:
          path: /todos
          method: get
  createTodo:
    handler: src/handlers/create-todo.handler
    events:
      - httpApi:
          path: /todos
          method: post
